version: '3'

services:
 challange-backend:
    image: bitnami/postgresql:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 4000:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
volumes:
  pgdata: