version: '3'

services:
 challange-backend:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 4000:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=challangeBackend